Repository mobsuccess-devops/github-actions-mobsuccess, pull requests merged in 2023-08, with the labels that each got.

#64 Add support for multiple amplify URIs in monorepos
  lib/actions/amplify.js
  lib/actions/pullRequest.js
Labels: feature

#65 Add support for AWS_AMPLIFY_URI as repository variable
  sample/workflows/mobsuccess.yml
Labels: feature

#66 Add support for running when a comment is made
  action.js
  lib/actions/amplify.js
  lib/actions/pullRequest.js
  sample/workflows/mobsuccess.yml
Labels: fix

#69 Add Display all monorepo amplify urls
  lib/actions/amplify.js
  lib/actions/pullRequest.js
Labels: core

#70 Fix destructuring undefined
  lib/actions/amplify.js
Labels: fix

#71 Fix styling of details
  lib/actions/pullRequest.js
Labels: fix
